services:
  postgres:
    container_name: criti-pixel-postgres
    hostname : criti-pixel-postgres
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    networks:
      lde-network:
    
networks:
  lde-network:
    external: true
    
volumes:
  postgres_db:
    driver: local
